<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE errorlist PUBLIC "-//Error Parser project//DTD Error Parser XML V1.3//EN"
             "http://errorparser.sourceforge.net/xml/errorParser13.dtd"> 
<!-- 
    This example is currently being used for an existing project, Photon
    to create code to retrieve error messages 
    using the error number.

    You can replace the DOCTYPE with this, if you prefer:
<!DOCTYPE errorlist SYSTEM 
             "/usr/local/share/xml/errorParser/DTD/errorParser13.dtd">
    
-->

<!-- Photon next version is 0.3 -->
<errorlist version="0.3">
  <!-- Copyright information and any additional info that will appear at 
       the top of the generated files. This is optional. -->
  <copyright_group>
    <copyright>
      <years>2006-2008</years>
      <authors>Daniel Prevost</authors>
      <!-- Each <license_para> is mapped to a paragraph (easier to read) -->
      <license_para>
        This file is part of Photon.
      </license_para>
      <!-- The GPL license is of course for Photon, not for Error Parser... -->
      <license_para>
        This file may be distributed and/or modified under the terms of the
        GNU General Public License version 2 as published by the Free Software
        Foundation and appearing in the file COPYING included in the
        packaging of this library.
      </license_para>
      <license_para>
        This library is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
      </license_para>
    </copyright>
  </copyright_group>
  <errgroup>
    <error>
      <errnumber> 0 </errnumber>
      <errname> OK </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>No error (adding a dummy % to test this feature)</errormsg>
          <errordoc>No error...</errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 666 </errnumber>
      <errname> INTERNAL_ERROR </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>Abnormal internal error.</errormsg>
          <errordoc>
            Abnormal internal error. It should not happen!
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 1 </errnumber>
      <errname> ENGINE_BUSY </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Cannot get a lock on a system object, the engine is "busy".
          </errormsg>
          <errordoc>
            Cannot get a lock on a system object, the engine is "busy".
          </errordoc>
          <errordoc>
            This might be the result of either a very busy system where 
            unused cpu cycles are rare or a lock might be held by a 
            crashed process.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 2 </errnumber>
      <errname> NOT_ENOUGH_PSO_MEMORY </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>Not enough memory in the PSO.</errormsg>
          <errordoc>Not enough memory in the PSO.</errordoc>
        </message>
      </message_group>
    </error>
 
    <error>
      <errnumber> 3 </errnumber>
      <errname> NOT_ENOUGH_HEAP_MEMORY </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Not enough heap memory (non-PSO memory). 
          </errormsg>
          <errordoc>
            Not enough heap memory (non-PSO memory).
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 4 </errnumber>
      <errname> NOT_ENOUGH_RESOURCES </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            There are not enough resources to correctly process the call.
          </errormsg>
          <errordoc>
            There are not enough resources to correctly process the call.
          </errordoc>
          <errordoc>
            Possible explanations: it might be a lack of POSIX semaphores 
            on systems where atomic locks are implemented that way or a 
            failure in initializing a pthread_mutex (or on Windows, a 
            critical section).
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 5 </errnumber>
      <errname> WRONG_TYPE_HANDLE </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The provided handle is of the wrong type.
          </errormsg>
          <errordoc>
            The provided handle is of the wrong type (C API). This could
            happen if you provide a queue handle to access a hash map or
            something similar. It can also occur if you try to access an
            object after closing it.
          </errordoc>
          <errordoc>
            If you are seeing this error for the C++ API (or some other
            object-oriented interface), you've just found an internal
            error... (the handle is encapsulated and cannot be modified
            using the public interface).
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 6 </errnumber>
      <errname> NULL_HANDLE </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The provided handle is NULL.
          </errormsg>
          <errordoc>
            The provided handle is NULL.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 7 </errnumber>
      <errname> NULL_POINTER </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            One of the arguments of an API function is an invalid NULL pointer.
          </errormsg>
          <errordoc>
            One of the arguments of an API function is an invalid NULL pointer.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 8 </errnumber>
      <errname> INVALID_LENGTH </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            An invalid length was provided.
          </errormsg>
          <errordoc>
            An invalid length was provided as an argument to an API function.
          </errordoc>
          <errordoc>
            This invalid length will usually indicate that the
            length value is set to zero.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 21 </errnumber>
      <errname> PROCESS_ALREADY_INITIALIZED </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The process was already initialized.
          </errormsg>
          <errordoc>
            The process was already initialized. 
            One possibility: was psoInit() called for a second time?
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 22 </errnumber>
      <errname> PROCESS_NOT_INITIALIZED </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The process was not properly initialized.
          </errormsg>
          <errordoc>
            The process was not properly initialized. One possibility: was psoInit() called?
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 23 </errnumber>
      <errname> INVALID_WATCHDOG_ADDRESS </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The watchdog address is invalid (empty string, NULL pointer, etc.).
          </errormsg>
          <errordoc>
            The watchdog address is invalid (empty string, NULL pointer, etc.).
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 24 </errnumber>
      <errname> INCOMPATIBLE_VERSIONS </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            API - memory-file version mismatch.
          </errormsg>
          <errordoc>
            API - memory-file version mismatch. 
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 25 </errnumber>
      <errname> SOCKET_ERROR </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Generic socket error.
          </errormsg>
          <errordoc>
            Generic socket error.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 26 </errnumber>
      <errname> CONNECT_ERROR </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Socket error when trying to connect to the watchdog.
          </errormsg>
          <errordoc>
            Socket error when trying to connect to the watchdog.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 27 </errnumber>
      <errname> SEND_ERROR </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Socket error when trying to send a request to the watchdog.
          </errormsg>
          <errordoc>
            Socket error when trying to send a request to the watchdog.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 28 </errnumber>
      <errname> RECEIVE_ERROR </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Socket error when trying to receive a reply from the watchdog.
          </errormsg>
          <errordoc>
            Socket error when trying to receive a reply from the watchdog.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 29 </errnumber>
      <errname> BACKSTORE_FILE_MISSING </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The shared-memory backstore file is missing.
          </errormsg>
          <errordoc>
            The shared-memory backstore file is missing. The name of this file is 
            provided by the server (quasar) - if it is missing, something really
            weird is going on.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 30 </errnumber>
      <errname> ERROR_OPENING_MEMORY </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Generic i/o error when attempting to open the shared memory.
          </errormsg>
          <errordoc>
            Generic i/o error when attempting to open the shared memory.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 41 </errnumber>
      <errname> LOGFILE_ERROR </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Error accessing the directory for the log files or error opening the 
            log file itself.
          </errormsg>
          <errordoc>
            Error accessing the directory for the log files or error opening 
            the log file itself.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 42 </errnumber>
      <errname> SESSION_CANNOT_GET_LOCK </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Cannot get a lock on the session (a pthread_mutex or a critical 
            section on Windows). 
          </errormsg>
          <errordoc>
            Cannot get a lock on the session (a pthread_mutex or a critical 
            section on Windows). 
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 43 </errnumber>
      <errname> SESSION_IS_TERMINATED </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            An attempt was made to use a session object (a session handle)
            after this session was terminated.
          </errormsg>
          <errordoc>
            An attempt was made to use a session object (a session handle)
            after this session was terminated.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 51 </errnumber>
      <errname> INVALID_OBJECT_NAME </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Permitted characters for names are alphanumerics, spaces (' '), 
            dashes ('-') and underlines ('_'). The first character
            must be alphanumeric.
          </errormsg>
          <errordoc>
            Permitted characters for names are alphanumerics, spaces (' '), 
            dashes ('-') and underlines ('_'). The first character
            must be alphanumeric.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 52 </errnumber>
      <errname> NO_SUCH_OBJECT </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The object was not found (but its folder does exist).
          </errormsg>
          <errordoc>
            The object was not found (but its folder does exist).
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 53 </errnumber>
      <errname> NO_SUCH_FOLDER </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            One of the parent folder of an object does not exist.
          </errormsg>
          <errordoc>
            One of the parent folder of an object does not exist.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 54 </errnumber>
      <errname> OBJECT_ALREADY_PRESENT </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Attempt to create an object which already exists.
          </errormsg>
          <errordoc>
            Attempt to create an object which already exists.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 55 </errnumber>
      <errname> IS_EMPTY </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The object (data container) is empty.
          </errormsg>
          <errordoc>
            The object (data container) is empty.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 56 </errnumber>
      <errname> WRONG_OBJECT_TYPE </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Attempt to create an object of an unknown object type or to open
            an object of the wrong type. 
          </errormsg>
          <errordoc>
            Attempt to create an object of an unknown object type or to open
            an object of the wrong type. 
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 57 </errnumber>
      <errname> OBJECT_CANNOT_GET_LOCK </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Cannot get lock on the object.
            This might be the result of either a very busy system where 
            unused cpu cycles are rare or a lock might be held by a 
            crashed process.
          </errormsg>
          <errordoc>
            Cannot get lock on the object.
            This might be the result of either a very busy system where 
            unused cpu cycles are rare or a lock might be held by a 
            crashed process.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 58 </errnumber>
      <errname> REACHED_THE_END </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The search/iteration reached the end without finding a new 
            item/record. 
          </errormsg>
          <errordoc>
            The search/iteration reached the end without finding a new 
            item/record. 
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 59 </errnumber>
      <errname> INVALID_ITERATOR </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            An invalid value was used for a psoIteratorType parameter.
          </errormsg>
          <errordoc>
            An invalid value was used for a psoIteratorType parameter.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 60 </errnumber>
      <errname> OBJECT_NAME_TOO_LONG </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The name of the object is too long.
            The maximum length of a name cannot be more than PSO_MAX_NAME_LENGTH
            (or PSO_MAX_FULL_NAME_LENGTH for the fully qualified name).
          </errormsg>
          <errordoc>
            The name of the object is too long.
            The maximum length of a name cannot be more than PSO_MAX_NAME_LENGTH
            (or PSO_MAX_FULL_NAME_LENGTH for the fully qualified name).
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 61 </errnumber>
      <errname> FOLDER_IS_NOT_EMPTY </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            You cannot delete a folder if there are still undeleted objects in
            it.
          </errormsg>
          <errordoc>
            You cannot delete a folder if there are still undeleted objects in
            it.
          </errordoc>
          <errordoc>
            Technical: a folder does not need to be empty to be deleted but
            all objects in it must be "marked as deleted" by the current session.
            This enables writing recursive deletions
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 62 </errnumber>
      <errname> ITEM_ALREADY_PRESENT </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            An item with the same key was found.
          </errormsg>
          <errordoc>
            An item with the same key was found.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 63 </errnumber>
      <errname> NO_SUCH_ITEM </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The item was not found in the hash map.
          </errormsg>
          <errordoc>
            The item was not found in the hash map.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 64 </errnumber>    
      <errname> OBJECT_IS_DELETED </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The object is scheduled to be deleted soon. Operations on this data
            container are not permitted at this time.
          </errormsg>
          <errordoc>
            The object is scheduled to be deleted soon. Operations on this data
            container are not permitted at this time.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 65 </errnumber>
      <errname> OBJECT_NOT_INITIALIZED </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Object must be open first before you can access them.
          </errormsg>
          <errordoc>
            Object must be open first before you can access them.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 66 </errnumber>
      <errname> ITEM_IS_IN_USE </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The data item is scheduled to be deleted soon or was just created and
            is not committed. Operations on this data item are not permitted 
            at this time.
          </errormsg>
          <errordoc>
            The data item is scheduled to be deleted soon or was just created and
            is not committed. Operations on this data item are not permitted 
            at this time.
          </errordoc>
        </message>
      </message_group>
    </error>
   
    <error>
      <errnumber> 67 </errnumber>
      <errname> ITEM_IS_DELETED </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The data item is scheduled to be deleted soon. Operations on this data
            container are not permitted at this time.
          </errormsg>
          <errordoc>
            The data item is scheduled to be deleted soon. Operations on this data
            container are not permitted at this time.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 69 </errnumber>
      <errname> OBJECT_IS_IN_USE </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The object is scheduled to be deleted soon or was just created and
            is not committed. Operations on this object are not permitted 
            at this time.
          </errormsg>
          <errordoc>
            The object is scheduled to be deleted soon or was just created and
            is not committed. Operations on this object are not permitted 
            at this time.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 70 </errnumber>
      <errname> OBJECT_IS_READ_ONLY </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The object is read-only and update operations on it are not 
            permitted.
          </errormsg>
          <errordoc>
            The object is read-only and update operations (delete/insert/replace)
            on it are not permitted.
            at this time.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 71 </errnumber>
      <errname> NOT_ALL_EDIT_ARE_CLOSED </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            All edits must be closed before a commit. 
          </errormsg>
          <errordoc>
            All read-only objects open for updates (as temporary objects)
            must be closed prior to doing a commit on the session.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 72 </errnumber>
      <errname> A_SINGLE_UPDATER_IS_ALLOWED </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            Read-only objects can only have one updater at a time.
          </errormsg>
          <errordoc>
            Read-only objects are not updated very frequently and therefore
            only a single editing copy is allowed. To allow concurrent editors
            (either all working on the same copy or each working with its 
            own copy would have been be possible but was deemed unnecessary.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 101 </errnumber>
      <errname> INVALID_NUM_FIELDS </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The number of fields in the data definition is invalid.
          </errormsg>
          <errordoc>
            The number of fields in the data definition is invalid - either 
            zero or greater than PSO_MAX_FIELDS (defined in photon/psoCommon.h).
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 102 </errnumber>
      <errname> INVALID_FIELD_TYPE </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The data type of the field definition is invalid.
          </errormsg>
          <errordoc>
            The data type of the field definition does not correspond to one of
            the data type defined in the enum psoFieldType (photon/psoCommon.h).
            or you've used PSO_VAR_STRING or PSO_VAR_BINARY at the wrong place.
          </errordoc>
          <errordoc> 
            Do not forget that PSO_VAR_STRING and PSO_VAR_BINAR can only be
            used for the last field of your data definition.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 103 </errnumber>
      <errname> INVALID_FIELD_LENGTH_INT </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The length of an integer field (PSO_INTEGER) is invalid.
          </errormsg>
          <errordoc>
            The length of an integer field (PSO_INTEGER) is invalid. Valid
            values are 1, 2, 4 and 8.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 104 </errnumber>
      <errname> INVALID_FIELD_LENGTH </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The length of a field (string or binary) is invalid.
          </errormsg>
          <errordoc>
            The length of a field (string or binary) is invalid. Valid
            values are all numbers greater than zero and less than 
            4294967296 (4 Giga).
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 105 </errnumber>
      <errname> INVALID_FIELD_NAME </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The name of the field contains invalid characters.
          </errormsg>
          <errordoc>
            The name of the field contains invalid characters. Valid
            characters are the standard ASCII alphanumerics ([a-zA-Z0-9])
            and the underscore ('_'). 
            The first character of the name must be letter.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 106 </errnumber>
      <errname> DUPLICATE_FIELD_NAME </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The name of the field is already used by another field in the
            current definition.
          </errormsg>
          <errordoc>
            The name of the field is already used by another field in the
            current definition.
          </errordoc>
          <errordoc>
            Note: at the moment field names are case sensitive (for
            example "account_id" and "Account_Id" are considered different).
            This might be changed eventually so this practice should
            be avoided.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 107 </errnumber>
      <errname> INVALID_PRECISION </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The precision of a PSO_DECIMAL field is invalid.
          </errormsg>
          <errordoc>
            The precision of a PSO_DECIMAL field is either zero or over the 
            limit for this type (set at 30 currently). Note: precision 
            is the number of digits in a number.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 108 </errnumber>
      <errname> INVALID_SCALE </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The scale of a PSO_DECIMAL field is invalid.
          </errormsg>
          <errordoc>
            The scale of a PSO_DECIMAL field is invalid (greater than the
            value of precision. Note: scale is the number of digits to the 
            right of the decimal separator in a number.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 109 </errnumber>
      <errname> INVALID_KEY_DEF </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The key definition is invalid or missing.
          </errormsg>
          <errordoc>
            The key definition for a hash map is either invalid or missing.
          </errordoc>
        </message>
      </message_group>
    </error>
  </errgroup>
  
  <errgroup>
    <errgroup_ident>
      <errgroup_name> XML Errors </errgroup_name>
      <errgroup_desc>
        A group of XML related errors (XML can be used to define data
        containers).
      </errgroup_desc>
    </errgroup_ident>
    <error>
      <errnumber> 201 </errnumber>
      <errname> XML_READ_ERROR</errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>Error reading the XML buffer.</errormsg>
          <errordoc>Error reading the XML buffer stream.</errordoc>
          <errordoc>
            No validation is done at this point. Therefore the error is likely
            something like a missing end-tag or some other non-conformance to 
            the XML's syntax rules. 
          </errordoc>
          <errordoc>
            A simple Google search for "well-formed xml" returns many web sites 
            that describe the syntax rules for XML. You can also use the 
            program xmllint (included in the distribution of libxm2) to
            pinpoint the issue.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 202 </errnumber>
      <errname> XML_INVALID_ROOT</errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>The root element is not the expected root.</errormsg>
          <errordoc>
            The root element is not the expected root, &lt;folder&gt; and
            similar.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 203 </errnumber>
      <errname> XML_NO_SCHEMA_LOCATION</errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>
            The attribute xsi:schemaLocation was not found or is invalid.
          </errormsg>
          <errordoc>
            The root element must have an attribute named schemaLocation (in 
            the namespace "http://www.w3.org/2001/XMLSchema-instance") to
            point to the schema use for the xml buffer stream.
          </errordoc>
          <errordoc>
            This attribute is in two parts separated by a space. The code
            expects the file name of the schema in the second element of
            this attribute.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 204 </errnumber>
      <errname> XML_PARSER_CONTEXT_FAILED</errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>The creation of a new schema parser context failed.</errormsg>
          <errordoc>
            The creation of a new schema parser context failed. There might
            be multiple reasons for this, for example, a memory-allocation
            failure in libxml2. However, the most likely reason is that the
            schema file is not at the location indicated by the attribute 
            schemaLocation of the root element of the buffer stream.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 205 </errnumber>
      <errname> XML_PARSE_SCHEMA_FAILED</errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>Failure when parsing the XML schema.</errormsg>
          <errordoc>
            The parse operation of the schema failed. Most likely, there
            is an error in the schema. To debug this
            you can use xmllint (part of the libxml2 package).
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 206 </errnumber>
      <errname> XML_VALID_CONTEXT_FAILED</errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>The creation of a new XML Schemas validation context failed.</errormsg>
          <errordoc>
            The creation of a new schema validation context failed. There might
            be multiple reasons for this, for example, a memory-allocation
            failure in libxml2.
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 207 </errnumber>
      <errname> XML_VALIDATION_FAILED</errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>Document validation for the xml buffer failed.</errormsg>
          <errordoc>
            Document validation for the xml buffer failed. To debug this
            problem you can use xmllint (part of the libxml2 package).
          </errordoc>
        </message>
      </message_group>
    </error>

    <error>
      <errnumber> 601 </errnumber>
      <errname> SEM_DESTROY_ERROR </errname>
      <message_group>
        <message xml:lang="en">
          <errormsg>Abnormal internal error with sem_destroy.</errormsg>
          <errordoc>
            Abnormal internal error with sem_destroy. It should not happen!
            It could indicate that the memory allocated for the semaphore 
            was corrupted (errno = EINVAL) or that the reference counting 
            is wrong (errno = EBUSY). Please contact us.
          </errordoc>
        </message>
      </message_group>
    </error>

  </errgroup>
    
  
</errorlist>

